name: WENDY
favicon: null
layout_spectrum: 0.56367
typography_spectrum: 0.09124702215194702
title: WENDY BANKS PORTRAITS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26221f'
    - '#5b544e'
    - '#756c65'
    - '#f6e4d7'
    - '#90867e'
  brandStrength: 0.16373984864912927
  lightness: 0.019435538910329342
  saturation: 0.26767909759655595
  rhythmicContrast: 0.08964318968355656
purpose: []
