name: WENDY BANKS PORTRAITS
favicon: null
layout_spectrum: 0.09242
typography_spectrum: 0.13192
title: WENDY BANKS PORTRAITS
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#26221f'
    - '#5b544e'
    - '#756c65'
    - '#f6e4d7'
    - '#90867e'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.26767909759655595
  rhythmicContrast: 0.08964318968355656
purpose: []
